### ISSUE TITLE
About the donation system

### ISSUE THREAD

**Issue by focaeppe** [enwillyado/xmrig#10]
I have question on how it works the donation system what we need to change exactly in the config or in the donate.h ?

**Comment by enwillyado** [comment]
See in https://github.com/enwillyado/xmrig/blob/master/CMakeLists.txt the `cmake` options: `-DXMRIG_NO_DONATE=ON` if you _need_ a miner **without donation time**. But, if active this flag, consider making a donation or participate in this fork actively like you are doing now.

If you like to adjust the donation time, view and edit https://github.com/enwillyado/xmrig/blob/master/src/donate.h comment or try to use the donation-related command line arguments:

* `--donate-url=xxx`
* `--donate-url-little=xxx` (only with AEON feature)
* `--donate-user=xxx`
* `--donate-pass=xxx`
* `--donate-userpass=xxx`
* `--donate-keepalive`
* `--donate-nicehash`
* `--donate-ssl` (only with SSL feature)
* `--donate-minutes=xxx`
* `--minutes-in-cicle=xxx`
