### ISSUE TITLE
Build on ubuntu 16.04

### ISSUE THREAD

**Issue by huynhnham1301** [enwillyado/xmrig#13]
-- Could NOT find OPENSSL_INCLUDE_DIR (missing:  OPENSSL_LIBRARY CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:180 (message):
  openssl NOT found: use `-DXMRIG_NO_SSL=ON` to build without SSL support

how to use  xmrig-noSSL_4.4.0-8_gcc_8.1.0_noarch

**Comment by enwillyado** [comment]
If you have not installed the OPENSSL lib, you need to generate with `XMRIG_NO_SSL` flag:

`cmake .. -DXMRIG_NO_SSL=ON `

If you need to install the OPENSSL lib, you can install it before generation with the next command (or equivalent):

`sudo apt-get install openssl openssl-dev`.
