### ISSUE TITLE
i get a error  while  compiling  xmrig-VW 

### ISSUE THREAD

**Issue by wayne3407** [enwillyado/xmrig#7]
-- Configuring done
CMake Error at CMakeLists.txt:220 (add_executable):
  Cannot find source file:

    src/3rdparty/libuv-tls/uv_tls.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: xmrig
CMake Error: Cannot determine link language for target "xmrig".
-- Generating done
Can you help me ?

**Comment by enwillyado** [comment]
The https://github.com/enwillyado/xmrig/releases/tag/VW-3.4.0-6 is a pre-release and it only works in MS VS environment. Use the latest main version or apply the current changes (https://github.com/enwillyado/xmrig/compare/VW-3.4.0-6...master), specially this: https://github.com/enwillyado/xmrig/compare/VW-3.4.0-6...master#diff-af3b638bc2a3e6c650974192a53c7291.

Greetings.

**Comment by wayne3407** [comment]
hi   when  i  compiling VW-3.3.4.5 ,i got  this error  😀 
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libuv.a: could not read symbols: No such file or directory
collect2: ld returned 1 exit status
make[2]: *** [xmrig] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2
----------------------------------------------------------------------------
[root@compute_XX xmrig-VW-3.3.4-5]# ll /usr/lib64/libuv.a
-rwxr-xr-x 1 root root 9426 Feb 25  2015 /usr/lib64/libuv.a

**Comment by wayne3407** [comment]
hi @enwillyado  thanks  ,I have already compiled  install the xmrig,but how  can i use it , i set the http_proxy in the /etc/profile and edit the config.json,"url": "xmr.f2pool.com:13531" ,please  tell me

**Comment by enwillyado** [comment]
@wayne3407 Check https://github.com/enwillyado/xmrig/blob/master/src/config.json, pool section:

>     "pools": [
>        {
>            "url": "xmr.f2pool.com:13531@localhost:8080",
>            "user": "<USER>",
>            "pass": "<PASS>",
>            "keepalive": true,
>            "nicehash": true,
>            "ssl": true,
>            "variant": -1
>        }
>     ],
>
You need to write the `localhost:8080` (`proxyhost:proxyport`) in the `url`. The `http_proxy` env variable does not works!

**Comment by wayne3407** [comment]
hi @enwillyado 

config.json
----------------------------------------------------------------------------------------------
 "syslog": false,
    "threads": null,
    "pools": [
        {
            "url": "xmr.f2pool.com:13531@10.228.0.116:8080",
            "user": "
            "pass": "x",
            "keepalive": true,
            "nicehash": true,
            "variant": -1
-------------------------------------------------------------------------------------------------
 xmrig
0x48439d * VERSIONS:     XMRig/3.3.4-5 libuv/1.20.1-dev gcc/4.4.7
0x48439d * THREADS:      10, cryptonight, av=1, donate-minutes=0
0x48439d * POOL #1:      10.228.0.116:8080
[2018-04-27 14:47:46] 0x48439dspeed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-04-27 14:47:46] 0x48439dspeed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-04-27 14:47:46] 0x48439dspeed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
--------------------------------------------------------------------------------------------
hi ,i have done as you say ,but  i cannot connect the pool either!
