### ISSUE TITLE
compatibility with last xmrig

### ISSUE THREAD

**Issue by 2010phenix** [enwillyado/xmrig#8]
can you plz update your work to the last source?
Thanks

**Comment by enwillyado** [comment]
It is compatible already. What feature is not included in this fork?

**Comment by 2010phenix** [comment]
xmrig build in dev branch xmrig-2.6.0-beta and etc

**Comment by enwillyado** [comment]
That is only code, and it is still beta; but, what new features does it have for users?

**Comment by 2010phenix** [comment]
algo support... devs do stupid things after fork update, move block, xor over xor and etc

**Comment by enwillyado** [comment]
@2010phenix by now, this fork is XMR oriented.

**Comment by 2010phenix** [comment]
@enwillyado Thx man.
