### ISSUE TITLE
SSL error (not supported)

### ISSUE THREAD

**Issue by focaeppe** [enwillyado/xmrig#9]
Thank you
After the compilation the miner doesn't work SSL error (not supported)even when i change "ssl": true, to false nothing change

**Comment by enwillyado** [comment]
@focaeppe You need to build it with the default `cmake` options (be sure that `-DXMRIG_NO_SSL` is not **ON**).

**Comment by focaeppe** [comment]
Thank you :)
I have another question on how it works the donation system what we need to change exactly in the config or in the donate.h ?

**Comment by enwillyado** [comment]
@focaeppe Please, if you have another question, open a new issue.

> PS. See in https://github.com/enwillyado/xmrig/blob/master/CMakeLists.txt the `cmake` options: `-DXMRIG_NO_DONATE=ON`. But, if active this flag, consider making a donation or participate in this fork actively like you are doing now.
